package Chloro::Manual;

# ABSTRACT: Learn how to use Chloro

__END__

=head1 MANUAL DOCUMENTS

The manual consists of a few documents:

=over 4

=item * L<Chloro::Manual::Intro>

The basics of Chloro. Learn how to define a form with basic fields, how to
process user input, and how to work with a resultset.

=item * L<Chloro::Manual::Groups>

Repeatable groups in Chloro.

=back

=cut
